var annotated_dup =
[
    [ "_sourceblocknode", "struct__sourceblocknode.html", "struct__sourceblocknode" ],
    [ "_sourcecode", "struct__sourcecode.html", "struct__sourcecode" ],
    [ "batch", "structbatch.html", "structbatch" ],
    [ "d2c_impl", "structd2c__impl.html", "structd2c__impl" ],
    [ "D2C_INDENT_STRUCT", "struct_d2_c___i_n_d_e_n_t___s_t_r_u_c_t.html", "struct_d2_c___i_n_d_e_n_t___s_t_r_u_c_t" ],
    [ "declaration", "structdeclaration.html", "structdeclaration" ],
    [ "endless_string", "structendless__string.html", "structendless__string" ],
    [ "endless_string_buf", "structendless__string__buf.html", "structendless__string__buf" ],
    [ "geometry", "structgeometry.html", "structgeometry" ],
    [ "ini_parse_command", "structini__parse__command.html", "structini__parse__command" ],
    [ "module", "structmodule.html", "structmodule" ],
    [ "namenode", "structnamenode.html", "structnamenode" ],
    [ "param_list", "structparam__list.html", "structparam__list" ],
    [ "sourceblock", "structsourceblock.html", "structsourceblock" ],
    [ "umlassocnode", "structumlassocnode.html", "structumlassocnode" ],
    [ "umlattribute", "structumlattribute.html", "structumlattribute" ],
    [ "umlattrnode", "structumlattrnode.html", "structumlattrnode" ],
    [ "umlclass", "structumlclass.html", "structumlclass" ],
    [ "umlclassnode", "structumlclassnode.html", "structumlclassnode" ],
    [ "umloperation", "structumloperation.html", "structumloperation" ],
    [ "umlopnode", "structumlopnode.html", "structumlopnode" ],
    [ "umlpackage", "structumlpackage.html", "structumlpackage" ],
    [ "umlpackagenode", "structumlpackagenode.html", "structumlpackagenode" ],
    [ "umltemplate", "structumltemplate.html", "structumltemplate" ],
    [ "umltemplatenode", "structumltemplatenode.html", "structumltemplatenode" ]
];